In [1]:
#importing dependencies
import pandas as pd , numpy as np 
from selenium import webdriver
import colorama
from colorama import Fore
from datetime import datetime

import warnings
warnings.filterwarnings("ignore")

%autosave 1

Autosaving every 1 seconds

In [2]:
# creating the list of dates 
list_of_dates = []

try:
    #taking input from user
    start_date = input("Enter start date (in YYYY MM DD) : " )
    end_date = input("Enter end date (in YYYY MM DD) : " )
#     end_date = '2022 4 15'
#     start_date = '2000 1 27'

    #adding up condition 
    if start_date > end_date :
        print(Fore.RED+ '\nstart date must come before end date')

    #appending to the list includes both dates
    else:
        for d in pd.date_range(start_date, end_date,inclusive="both"):
            list_of_dates.append(d.strftime("%b %#d, %Y"))

#dealing with error/s    
except ValueError:
    print(Fore.RED +"\nAdd the dates in correct format (in YYYY MM DD)")

Enter start date (in YYYY MM DD) : 2000 1 1
Enter end date (in YYYY MM DD) : 2022 4 15

In [3]:
#driver for operation
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())

====== WebDriver manager ======
Current google-chrome version is 100.0.4896
Get LATEST chromedriver version for 100.0.4896 google-chrome
Driver [C:\Users\AKSHAY SATPUTE\.wdm\drivers\chromedriver\win32\100.0.4896.60\chromedriver.exe] found in cache

In [4]:
url = 'https://www.oracle.com/news/'

#getting the url
driver.get(url)

#defining the seed
# if in future it is giving error then try increasing the seed value
seed = 1000

#using try except so that our operation will run smoothly.
try:
    for more in range(seed):
        #clicking on see more button
        driver.find_element_by_xpath('''//*[@id="__next"]/div/div[2]/div/div[1]/section/div/div[2]/div''').click()
        
except:
    pass

In [5]:
#letting the operation to sleep so required script will run in the backend 
import time
time.sleep(2)

In [6]:
#creating the lists 
titles = []
dates = []
urls = []

try:
    for number in range(1,seed):
        
        #getting all of the dates avilable
        date = driver.find_element_by_xpath(f'''//*[@id="__next"]/div/div[2]/div/div[1]/section/div/div/div[{number}]/div[1]/div''').text
        
        #moving forward only if the date is in list_of dates 
        if date in list_of_dates :
            print(f"found date in news {date}")
            date = driver.find_element_by_xpath(f'''//*[@id="__next"]/div/div[2]/div/div[1]/section/div/div/div[{number}]/div[1]/div''').text
            dates.append(date)
            title = driver.find_element_by_xpath(f'''//*[@id="__next"]/div/div[2]/div/div[1]/section/div/div/div[{number}]/div[2]/h5/a''').text
            titles.append(title)
            href = driver.find_element_by_xpath(f'''//*[@id="__next"]/div/div[2]/div/div[1]/section/div/div/div[{number}]/div[2]/h5/a''').get_attribute('href')
            urls.append(href)
#             print(f"{title}\n{date}\n{href}\n")
except:
    pass

found date in news Apr 13, 2022
found date in news Apr 13, 2022
found date in news Apr 12, 2022
found date in news Apr 12, 2022
found date in news Apr 11, 2022
found date in news Apr 7, 2022
found date in news Apr 7, 2022
found date in news Apr 7, 2022
found date in news Apr 5, 2022
found date in news Apr 4, 2022
found date in news Apr 1, 2022
found date in news Mar 30, 2022
found date in news Mar 29, 2022
found date in news Mar 24, 2022
found date in news Mar 24, 2022
found date in news Mar 22, 2022
found date in news Mar 17, 2022
found date in news Mar 16, 2022
found date in news Mar 16, 2022
found date in news Mar 16, 2022
found date in news Mar 15, 2022
found date in news Mar 15, 2022
found date in news Mar 14, 2022
found date in news Mar 14, 2022
found date in news Mar 10, 2022
found date in news Feb 24, 2022
found date in news Feb 16, 2022
found date in news Feb 15, 2022
found date in news Feb 15, 2022
found date in news Feb 14, 2022
found date in news Feb 14, 2022
found date in news Feb 14, 2022
found date in news Feb 13, 2022
found date in news Feb 10, 2022
found date in news Feb 10, 2022
found date in news Feb 9, 2022
found date in news Feb 9, 2022
found date in news Feb 7, 2022
found date in news Feb 3, 2022
found date in news Feb 1, 2022
found date in news Jan 31, 2022
found date in news Jan 27, 2022
found date in news Jan 26, 2022
found date in news Jan 25, 2022
found date in news Jan 24, 2022
found date in news Jan 19, 2022
found date in news Jan 19, 2022
found date in news Jan 19, 2022
found date in news Jan 19, 2022
found date in news Jan 19, 2022
found date in news Jan 18, 2022
found date in news Jan 18, 2022
found date in news Jan 12, 2022
found date in news Jan 12, 2022
found date in news Jan 11, 2022
found date in news Jan 11, 2022
found date in news Jan 11, 2022
found date in news Dec 14, 2021
found date in news Nov 9, 2021
found date in news Oct 13, 2021
found date in news Oct 7, 2021
found date in news Aug 3, 2021
found date in news Jun 7, 2021
found date in news May 20, 2021
found date in news May 19, 2021
found date in news May 3, 2021
found date in news Apr 27, 2021
found date in news Apr 23, 2021
found date in news Mar 31, 2021
found date in news Mar 23, 2021
found date in news Mar 15, 2021
found date in news Mar 3, 2021
found date in news Feb 25, 2021
found date in news Feb 24, 2021
found date in news Feb 16, 2021
found date in news Feb 9, 2021
found date in news Jan 20, 2021
found date in news Jan 7, 2021
found date in news Dec 22, 2020
found date in news Dec 14, 2020
found date in news Nov 10, 2020
found date in news Nov 3, 2020
found date in news Oct 5, 2020
found date in news Oct 2, 2020
found date in news Sep 30, 2020
found date in news Sep 30, 2020
found date in news Sep 30, 2020
found date in news Sep 29, 2020
found date in news Sep 28, 2020
found date in news Sep 23, 2020
found date in news Sep 22, 2020
found date in news Sep 17, 2020
found date in news Aug 28, 2020
found date in news Aug 25, 2020
found date in news Aug 24, 2020
found date in news Aug 13, 2020
found date in news Aug 11, 2020
found date in news Aug 10, 2020
found date in news Aug 6, 2020
found date in news Aug 5, 2020

In [7]:
#zippling the list so that it'll form the tuple
zipped = list(zip(dates,titles,urls))
zipped[:5]

[('Apr 13, 2022',
  'Oracle Helps National Grid Cut Carbon through Weatherization',
  'https://www.oracle.com/news/announcement/oracle-helps-national-grid-cut-carbon-through-weatherization-2022-04-13/'),
 ('Apr 13, 2022',
  'Oracle Launches Complete Employee Experience Platform for Evolving Workforce Needs',
  'https://www.oracle.com/news/announcement/oracle-launches-complete-employee-experience-platform-2022-04-13/'),
 ('Apr 12, 2022',
  'These Oracle Customers Are the Change Agents Our Planet Needs',
  'https://blogs.oracle.com/sustainability/post/these-oracle-customers-are-the-change-agents-our-planet-needs'),
 ('Apr 12, 2022',
  'Transportation Management Systems Are Key to Driving Supply Chain Efficiency and Value',
  'https://www.oracle.com/news/announcement/blog/transportation-management-systems-are-key-to-driving-supply-chain-efficiency-and-value-2022-04-12/'),
 ('Apr 11, 2022',
  'City of Tampa Redesigns Staff Operations with Oracle Fusion Cloud Applications',
  'https://www.oracle.com/news/announcement/tampa-redesigns-staff-operations-with-oracle-fusion-cloud-applications-2022-04-11/')]

In [8]:
#creating dataframe 
temp_df = pd.DataFrame(zipped,columns=['date','title','url'])
temp_df

,date,title,url
0,"Apr 13, 2022",Oracle Helps National Grid Cut Carbon through ...,https://www.oracle.com/news/announcement/oracl...
1,"Apr 13, 2022",Oracle Launches Complete Employee Experience P...,https://www.oracle.com/news/announcement/oracl...
2,"Apr 12, 2022",These Oracle Customers Are the Change Agents O...,https://blogs.oracle.com/sustainability/post/t...
3,"Apr 12, 2022",Transportation Management Systems Are Key to D...,https://www.oracle.com/news/announcement/blog/...
4,"Apr 11, 2022",City of Tampa Redesigns Staff Operations with ...,https://www.oracle.com/news/announcement/tampa...
...,...,...,...
95,"Aug 13, 2020",Launch of Autonomous JSON Database,https://blogs.oracle.com/jsondb/autonomous-jso...
96,"Aug 11, 2020",The Key Role of Warehouse Management in Buildi...,https://blogs.oracle.com/scm/the-key-role-of-w...
97,"Aug 10, 2020",Stories from the Cloud: Call Centers of Excell...,https://soundcloud.com/stories-from-the-cloud/...
98,"Aug 6, 2020",Oracle Helps Marketers Navigate Changes and Ma...,https://blogs.oracle.com/marketingcloud/oracle...
99,"Aug 5, 2020",Oracle Cloud Infrastructure Behind World's Fas...,https://blogs.oracle.com/cloud-infrastructure/...

In [9]:
import re 
import time
time.sleep(3)

In [10]:
#creating list for articles
articles =[]

try:
    for x in range(len(temp_df)):
        
        url = temp_df['url'][x]
        
        #getting the url,refreshing the page and letting wait for some time
        driver.get(url)
        driver.refresh()
        time.sleep(3)
        
        #the below loop is able to generate the articles 
        #can mark the invalid links 
        #can report the links which are new
        
        if len(re.findall('https://blogs.oracle.com/',url)) != 0:
            try:
                article = driver.find_element_by_xpath('''/html/body/div/div[2]/div/div/div/div''').text
                articles.append(article)
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")
                print(url)
                print()

        elif len(re.findall('http://blogs.oracle.com/',url)) != 0:
            try:
                article = driver.find_element_by_xpath('''//*[@id="ab0f5670-4ae1-4b02-b02b-6d2e71bb01b1"]/div/div''').text
                articles.append(article)
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")            
                print(url)
                print()
 
        elif len(re.findall('https://www.oracle.com/emea/news/',url)) != 0:
        
            try:                                          
                article = driver.find_element_by_xpath('''/html/body/div/section[2]/div''').text
                articles.append(article)
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")
                print(url)
                print()
                
        elif len(re.findall('https://www.oracle.com/',url)) != 0:
            try:
                article = driver.find_element_by_xpath('''//*[@id="__next"]/div/section[2]/div''').text
                articles.append(article)
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")
                print(url)
                print()
                
                
        elif len(re.findall('https://soundcloud.com/',url)) != 0:
            try:
                article = driver.find_element_by_xpath('''//*[@id="content"]/div/div[3]/div[1]/div/div[2]/div[2]/div/div[2]/div/div/div/div[1]/div''').text
                articles.append(article +"\n" + "to load more sign in via link" )
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")
                print(url)
                print()
                
        elif len(re.findall('https://investor.oracle.com/',url)) != 0:
            try:
                article = driver.find_element_by_xpath('''//*[@id="_ctrl0_ctl42_divModuleContainer"]/div''').text
                articles.append(article)
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")
                print(url)
                print()
                
        elif len(re.findall('https://medium.com/',url)) != 0:
            try:
                article = driver.find_element_by_xpath('''//*[@id="root"]/div/div[3]/div/div/main/div/div[3]/div[1]''').text
                articles.append(article)
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")
                print(url)
                print()
                
        elif len(re.findall('https://www.linkedin.com/',url)) != 0:
            try:
                article = driver.find_element_by_xpath('''//*[@id="main-content"]/section[1]/div/article''').text
                articles.append(article)
                print(Fore.GREEN + f"scrapping done for url {x}\n")
            except :
                articles.append("Invalid url")
                print(Fore.RED + f"Invalid url at {x}")
                print(url)
                print()
                
        else:
            print(Fore.BLACK + f"new url found at {x} row")
            print(temp_df['url'][x])
            print()

except:
    pass

scrapping done for url 0

scrapping done for url 1

scrapping done for url 2

scrapping done for url 3

scrapping done for url 4

scrapping done for url 5

scrapping done for url 6

scrapping done for url 7

scrapping done for url 8

scrapping done for url 9

scrapping done for url 10

scrapping done for url 11

scrapping done for url 12

scrapping done for url 13

scrapping done for url 14

scrapping done for url 15

scrapping done for url 16

scrapping done for url 17

scrapping done for url 18

scrapping done for url 19

scrapping done for url 20

scrapping done for url 21

scrapping done for url 22

scrapping done for url 23

scrapping done for url 24

scrapping done for url 25

scrapping done for url 26

scrapping done for url 27

scrapping done for url 28

scrapping done for url 29

scrapping done for url 30

scrapping done for url 31

scrapping done for url 32

scrapping done for url 33

scrapping done for url 34

scrapping done for url 35

scrapping done for url 36

scrapping done for url 37

scrapping done for url 38

scrapping done for url 39

scrapping done for url 40

scrapping done for url 41

scrapping done for url 42

scrapping done for url 43

scrapping done for url 44

scrapping done for url 45

scrapping done for url 46

scrapping done for url 47

scrapping done for url 48

scrapping done for url 49

scrapping done for url 50

scrapping done for url 51

scrapping done for url 52

scrapping done for url 53

scrapping done for url 54

scrapping done for url 55

scrapping done for url 56

scrapping done for url 57

scrapping done for url 58

scrapping done for url 59

scrapping done for url 60

scrapping done for url 61

scrapping done for url 62

scrapping done for url 63

scrapping done for url 64

scrapping done for url 65

Invalid url at 66
http://blogs.oracle.com/oem/announcing-oracle-enterprise-manager-13c-release-5

scrapping done for url 67

Invalid url at 68
https://www.oracle.com/a/ocom/docs/national-security-cloud-paper.pdf

scrapping done for url 69

scrapping done for url 70

scrapping done for url 71

scrapping done for url 72

scrapping done for url 73

scrapping done for url 74

scrapping done for url 75

scrapping done for url 76

scrapping done for url 77

scrapping done for url 78

scrapping done for url 79

scrapping done for url 80

scrapping done for url 81

scrapping done for url 82

scrapping done for url 83

scrapping done for url 84

scrapping done for url 85

scrapping done for url 86

scrapping done for url 87

scrapping done for url 88

scrapping done for url 89

scrapping done for url 90

scrapping done for url 91

scrapping done for url 92

scrapping done for url 93

scrapping done for url 94

Invalid url at 95
https://blogs.oracle.com/jsondb/autonomous-json-database

scrapping done for url 96

scrapping done for url 97

scrapping done for url 98

scrapping done for url 99

In [11]:
#adding the output to the dataframe
temp_df['article'] = articles
temp_df

,date,title,url,article
0,"Apr 13, 2022",Oracle Helps National Grid Cut Carbon through ...,https://www.oracle.com/news/announcement/oracl...,Press Release\nOracle Helps National Grid Cut ...
1,"Apr 13, 2022",Oracle Launches Complete Employee Experience P...,https://www.oracle.com/news/announcement/oracl...,Press Release\nOracle Launches Complete Employ...
2,"Apr 12, 2022",These Oracle Customers Are the Change Agents O...,https://blogs.oracle.com/sustainability/post/t...,These Oracle Customers Are The Change Agents O...
3,"Apr 12, 2022",Transportation Management Systems Are Key to D...,https://www.oracle.com/news/announcement/blog/...,Blog\nTransportation Management Systems Are Ke...
4,"Apr 11, 2022",City of Tampa Redesigns Staff Operations with ...,https://www.oracle.com/news/announcement/tampa...,Press Release\nCity of Tampa Redesigns Staff O...
...,...,...,...,...
95,"Aug 13, 2020",Launch of Autonomous JSON Database,https://blogs.oracle.com/jsondb/autonomous-jso...,Invalid url
96,"Aug 11, 2020",The Key Role of Warehouse Management in Buildi...,https://blogs.oracle.com/scm/the-key-role-of-w...,"Manufacturing, Oracle Supply Chain Management\..."
97,"Aug 10, 2020",Stories from the Cloud: Call Centers of Excell...,https://soundcloud.com/stories-from-the-cloud/...,"Knowledge is power. And in the business world,..."
98,"Aug 6, 2020",Oracle Helps Marketers Navigate Changes and Ma...,https://blogs.oracle.com/marketingcloud/oracle...,"Account Based Marketing, Customer Loyalty, Dat..."
99,"Aug 5, 2020",Oracle Cloud Infrastructure Behind World's Fas...,https://blogs.oracle.com/cloud-infrastructure/...,"Partner Solutions, Technical Solutions\nOracle..."

In [12]:
#the invalid links are marked as invalid url
#the urls is invalid if either the given url changes after opening or a wrong url
#for example there was a link of the pdf which is identified as invalid url 
temp_df.isna().sum()

date       0
title      0
url        0
article    0
dtype: int64

In [13]:
#saving the csv and keeping the index as false
temp_df.to_csv('Oracle all news release urls.csv',index=False)

In [14]:
#checking the dataframe
pd.read_csv('Oracle all news release urls.csv')

,date,title,url,article
0,"Apr 13, 2022",Oracle Helps National Grid Cut Carbon through ...,https://www.oracle.com/news/announcement/oracl...,Press Release\nOracle Helps National Grid Cut ...
1,"Apr 13, 2022",Oracle Launches Complete Employee Experience P...,https://www.oracle.com/news/announcement/oracl...,Press Release\nOracle Launches Complete Employ...
2,"Apr 12, 2022",These Oracle Customers Are the Change Agents O...,https://blogs.oracle.com/sustainability/post/t...,These Oracle Customers Are The Change Agents O...
3,"Apr 12, 2022",Transportation Management Systems Are Key to D...,https://www.oracle.com/news/announcement/blog/...,Blog\nTransportation Management Systems Are Ke...
4,"Apr 11, 2022",City of Tampa Redesigns Staff Operations with ...,https://www.oracle.com/news/announcement/tampa...,Press Release\nCity of Tampa Redesigns Staff O...
...,...,...,...,...
95,"Aug 13, 2020",Launch of Autonomous JSON Database,https://blogs.oracle.com/jsondb/autonomous-jso...,Invalid url
96,"Aug 11, 2020",The Key Role of Warehouse Management in Buildi...,https://blogs.oracle.com/scm/the-key-role-of-w...,"Manufacturing, Oracle Supply Chain Management\..."
97,"Aug 10, 2020",Stories from the Cloud: Call Centers of Excell...,https://soundcloud.com/stories-from-the-cloud/...,"Knowledge is power. And in the business world,..."
98,"Aug 6, 2020",Oracle Helps Marketers Navigate Changes and Ma...,https://blogs.oracle.com/marketingcloud/oracle...,"Account Based Marketing, Customer Loyalty, Dat..."
99,"Aug 5, 2020",Oracle Cloud Infrastructure Behind World's Fas...,https://blogs.oracle.com/cloud-infrastructure/...,"Partner Solutions, Technical Solutions\nOracle..."